version: '2'
services: 
  db:
    build: ./db
    restart: always
    environment:
      - POSTGRES_USER=covid
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=covid19_data
    ports: 
      - 9001:5432
    volumes:
      - ./db/db_data:/var/lib/postgresql/data
